import type { Metadata } from "next";
import { gasoekOne, bricolageGrotesque } from "./fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Lighthouse",
  description: "Generated by create next app", // TODO: update this
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${gasoekOne.variable} ${bricolageGrotesque.variable} `}
    >
      <body>{children}</body>
    </html>
  );
}
